### MONGO
MONGO_CONNECTION_STRING = "localhost:27017"
MONGO_FILMS_TABLE = "film"
MONGO_FILMS_LIKES_TABLE = "like_dislike"
MONGO_FILMS_RATINGS_TABLE = "film_user_rating"
MONGO_USERS_TABLE = "user"
MONGO_USER_RECOMS_TABLE = "user_recommendations"
MONGO_FILMS_TOP_TABLE = "film_top"

### SERVICE
DEFAULT_USER_ACTIVITY_LIMIT = 10
DEFAULT_TOP_LIMIT = 20
DEFAULT_TOP_RATING = 7
DEFAULT_COSINE_LIMIT = 0.25
